FROM node:22.18-alpine AS build
RUN corepack enable
WORKDIR /app
COPY . .
RUN pnpm install && pnpm --filter @symphoneer-hub/worker... build

FROM node:22.18-alpine
RUN corepack enable
WORKDIR /app
COPY --from=build /app /app
ENV NODE_ENV=production
CMD ["pnpm", "--filter", "@symphoneer-hub/worker", "start"]
